from .core import (
    add_position,
    compare_providers,
    analyze_prices,
    create_price_alert,
    evaluate_price_alerts,
    fetch_data,
    get_api_key,
    APIError,
    RateLimitError,
    InvalidSymbolError,
    list_positions,
    list_price_alerts,
    load_quotes,
    moving_average_crossover_backtest,
    portfolio_value,
    save_quote,
)
from .providers import (
    FinnhubClient,
    AlphaVantageClient,
    fetch_finnhub_news,
    fetch_trading_news,
)

__version__ = "0.1.0"
__all__ = [
    "fetch_data",
    "get_api_key",
    "APIError",
    "RateLimitError",
    "InvalidSymbolError",
    "add_position",
    "compare_providers",
    "analyze_prices",
    "FinnhubClient",
    "AlphaVantageClient",
    "create_price_alert",
    "evaluate_price_alerts",
    "list_positions",
    "list_price_alerts",
    "load_quotes",
    "fetch_finnhub_news",
    "fetch_trading_news",
    "moving_average_crossover_backtest",
    "portfolio_value",
    "save_quote",
]